import { useCallback, useEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Activity, Bluetooth, Check, CircleAlert, Cpu, Database, GripVertical, Lightbulb, Pin, Play, Settings, SlidersHorizontal, Sparkles, Trash2, Wifi, X } from "lucide-react";

type State = "无任务"|"进行中"|"等待操作"|"已完成"|"警告"|"失败";
type Task = {id:string;name:string;source:string;state:State;progress:number;color:string;updated:number;pinned:boolean};
type Dashboard = {tasks:Array<{task_id:string;title:string;source:string;state:string;progress:number;occurred_at_ms:number;pinned:number}>;metrics:{busy_percent:number;five_hour_tokens:number;seven_day_tokens:number}};
const demoTasks: Task[] = [
  {id:"demo-1",name:"等待本地数据",source:"示例",state:"进行中",progress:0,color:"#5b8ff9",updated:Date.now(),pinned:false},
];
type StyleConfig={color:string;effect:number;frequency:number;duty:number;automatic:boolean};
type Styles=Record<string,StyleConfig>;
const defaultStyles:Styles={running:{color:"#5b8ff9",effect:3,frequency:50,duty:50,automatic:true},waiting:{color:"#f6bd4b",effect:2,frequency:60,duty:20,automatic:true},success:{color:"#5ac49d",effect:1,frequency:30,duty:100,automatic:false},warning:{color:"#f38b75",effect:2,frequency:90,duty:25,automatic:true},failure:{color:"#d96770",effect:2,frequency:120,duty:20,automatic:true}};

function Toggle({on=true}:{on?:boolean}){return <span className={`toggle ${on?"on":""}`}><span/></span>}
function App(){
 const [page,setPage]=useState<"tasks"|"settings">("tasks");
 const [brightness,setBrightness]=useState(60);
 const [tasks,setTasks]=useState<Task[]>(demoTasks);
 const [metrics,setMetrics]=useState({busy_percent:0,five_hour_tokens:0,seven_day_tokens:0});
 const [backendError,setBackendError]=useState("");
 const [preview,setPreview]=useState(false);
 const [previewOpen,setPreviewOpen]=useState(false);
 const [previewRemaining,setPreviewRemaining]=useState(75);
 const [previewBusy,setPreviewBusy]=useState(35);
 const [previewStates,setPreviewStates]=useState(["running","waiting","success","warning","failure"]);
 const [saveState,setSaveState]=useState<"idle"|"saving"|"success"|"error">("idle");
 const [taskSlotCount,setTaskSlotCount]=useState(5);
 const refreshing=useRef(false);
 const refresh=useCallback(async()=>{if(refreshing.current)return;refreshing.current=true;try{const data=await invoke<Dashboard>("get_dashboard"); const names:Record<string,State>={idle:"无任务",running:"进行中",waiting:"等待操作",success:"已完成",warning:"警告",failure:"失败"}; const colors:Record<State,string>={"无任务":"#9aa3b2","进行中":"#5b8ff9","等待操作":"#f6bd4b","已完成":"#5ac49d","警告":"#f38b75","失败":"#d96770"}; setTasks(data.tasks.map(t=>{const state=names[t.state]??"警告";return {id:t.task_id,name:t.title,source:t.source,state,progress:t.progress,color:colors[state],updated:t.occurred_at_ms,pinned:Boolean(t.pinned)}}));setMetrics(data.metrics);setBackendError("")}catch(error){setBackendError(String(error))}finally{refreshing.current=false}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),2000);return()=>clearInterval(timer)},[refresh]);
 useEffect(()=>{invoke<{led_count:number}>("bridge_action",{action:"settings",payload:{}}).then(data=>setTaskSlotCount(Math.max(1,data.led_count-1)))},[]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;setSaveState(detail==="success"?"success":"error");setTimeout(()=>setSaveState("idle"),2200)};window.addEventListener("save-result",handler);return()=>window.removeEventListener("save-result",handler)},[]);
 return <div className="shell">
  <aside>
   <div className="brand"><span className="brandmark"><Sparkles size={19}/></span><div><strong>Beacon</strong><small>信标</small></div></div>
   <nav><button className={page==="tasks"?"active":""} onClick={()=>setPage("tasks")}><Activity/>任务面板</button><button className={page==="settings"?"active":""} onClick={()=>setPage("settings")}><Settings/>配置</button></nav>
   <div className="device"><div className="device-title"><span className={backendError?"":"online"}/><span>{backendError?"后台未连接":"本地核心已连接"}</span><Bluetooth size={15}/></div><strong>Beacon Light · 6 灯</strong><small>{backendError||"SQLite / 多来源实时同步"}</small></div>
   <div className="version">v0.1.0 · 本地运行</div>
  </aside>
  <main>
   <header><div><h1>{page==="tasks"?"任务面板":"灯板配置"}</h1><p>{page==="tasks"?"实时查看任务状态与灯位映射":"调整设备、灯效和数据源"}</p></div><div className="header-actions"><button className={preview?"preview-active":"ghost"} onClick={()=>setPreviewOpen(true)}><Play size={16}/>{preview?"正在预览":"设置状态并预览"}</button><button className={`primary save-${saveState}`} disabled={saveState==="saving"} onClick={()=>{setSaveState("saving");window.dispatchEvent(new Event("save-and-apply"))}}>{saveState==="saving"?"正在保存…":saveState==="success"?"已保存并生效":saveState==="error"?"保存失败":"保存并生效"}</button></div></header>
   {page==="tasks"?<TaskPage tasks={tasks} setTasks={setTasks} metrics={metrics} refresh={refresh} taskSlotCount={taskSlotCount}/>:<SettingsPage brightness={brightness} setBrightness={setBrightness}/>} 
  </main>
  {previewOpen&&<div className="modal-backdrop"><div className="preview-modal"><div className="modal-head"><div><h2>设置状态并预览</h2><p>这里只设置 Mock 状态，不会覆盖正式任务数据</p></div><button className="icon-button" onClick={async()=>{if(preview){await invoke("bridge_action",{action:"apply-device",payload:{preview:false}});setPreview(false)}setPreviewOpen(false)}}><X size={18}/></button></div><section className="preview-system"><h3>第一颗系统灯</h3><label>总体额度剩余 <input type="range" min="0" max="100" value={previewRemaining} onChange={e=>setPreviewRemaining(+e.target.value)}/><b>{previewRemaining}%</b></label><label>短时繁忙程度 <input type="range" min="0" max="100" value={previewBusy} onChange={e=>setPreviewBusy(+e.target.value)}/><b>{previewBusy}%</b></label></section><section><h3>任务灯状态</h3><div className="preview-tasks">{previewStates.map((state,index)=><label key={index}><span>灯位 {index+1}</span><select value={state} onChange={e=>setPreviewStates(old=>old.map((value,i)=>i===index?e.target.value:value))}><option value="idle">无任务</option><option value="running">进行中</option><option value="waiting">等待操作</option><option value="success">已完成</option><option value="warning">警告</option><option value="failure">失败</option></select></label>)}</div></section><div className="modal-actions"><button onClick={async()=>{if(preview){await invoke("bridge_action",{action:"apply-device",payload:{preview:false}});setPreview(false)}setPreviewOpen(false)}}>结束预览并恢复正式数据</button><span/><button className="primary" onClick={async()=>{try{await invoke("bridge_action",{action:"apply-device",payload:{preview:true,preview_states:previewStates,remaining_percent:previewRemaining,busy_percent:previewBusy}});setPreview(true)}catch(e){setBackendError(String(e))}}}>应用预览数据</button></div></div></div>}
 </div>
}
function TaskPage({tasks,setTasks,metrics,refresh,taskSlotCount}:{tasks:Task[];setTasks:(tasks:Task[])=>void;metrics:Dashboard["metrics"];refresh:()=>Promise<void>;taskSlotCount:number}){
 const [selected,setSelected]=useState<Set<string>>(new Set());
 const [dragged,setDragged]=useState<string|null>(null);
 const [dragPoint,setDragPoint]=useState<{x:number;y:number}|null>(null);
 const orderRef=useRef(tasks),draggedRef=useRef<string|null>(null);
 useEffect(()=>{orderRef.current=tasks},[tasks]);
 const action=async(payload:object)=>{await invoke("bridge_action",{action:"manage-tasks",payload});await refresh()};
 const toggle=(id:string)=>setSelected(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next});
 const previewMove=(target:string)=>{const moving=draggedRef.current;if(!moving||moving===target)return;const next=[...orderRef.current],from=next.findIndex(t=>t.id===moving),to=next.findIndex(t=>t.id===target);if(from<0||to<0)return;const [item]=next.splice(from,1);next.splice(to,0,item);orderRef.current=next;setTasks(next)};
 useEffect(()=>{const move=(event:PointerEvent)=>{if(draggedRef.current)setDragPoint({x:event.clientX,y:event.clientY})};const finish=()=>{const moving=draggedRef.current;if(!moving)return;draggedRef.current=null;setDragged(null);setDragPoint(null);document.body.classList.remove("task-dragging");const next=[...orderRef.current],targetSlot=next.findIndex(t=>t.id===moving);void action({operation:"reorder",task_ids:next.map(t=>t.id),dragged_id:moving,target_slot:targetSlot<taskSlotCount?targetSlot:null})};window.addEventListener("pointermove",move);window.addEventListener("pointerup",finish);window.addEventListener("pointercancel",finish);return()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",finish);window.removeEventListener("pointercancel",finish)}},[taskSlotCount]);
 const draggedTask=dragged?tasks.find(task=>task.id===dragged):null;
 return <>
 <section className="metrics">
  <Metric icon={<Cpu/>} title="繁忙程度" value={`${metrics.busy_percent}%`} detail="任务与 Token 综合" tone="blue"/>
  <Metric icon={<Activity/>} title="五小时用量" value={formatTokens(metrics.five_hour_tokens)} detail="Tokens · 本机统计" tone="mint"/>
  <Metric icon={<Database/>} title="七天用量" value={formatTokens(metrics.seven_day_tokens)} detail="Tokens · 本机统计" tone="violet"/>
 </section>
 <section className="card tasks"><div className="section-head"><div><h2>任务与灯位</h2><p>从拖动手柄调整灯位；固定后不会被自动任务顶替</p></div><div className="filters"><button><SlidersHorizontal size={15}/>全部状态</button><button disabled={!selected.size} onClick={()=>void action({operation:"delete",task_ids:[...selected]}).then(()=>setSelected(new Set()))}><Trash2 size={15}/>删除选中</button><button onClick={()=>void action({operation:"delete-completed"})}>清理已完成</button></div></div>
 <div className="task-table"><div className="table-head"><span>操作</span><span>灯位</span><span>任务</span><span>来源</span><span>状态</span></div>{tasks.map((t,i)=><div className={`task-row ${selected.has(t.id)?"selected":""} ${dragged===t.id?"dragging":""} ${i>=taskSlotCount?"off-strip":""} ${i===taskSlotCount?"first-off-strip":""}`} key={t.id} onPointerEnter={()=>previewMove(t.id)}><span className="row-actions"><input aria-label="选择任务" type="checkbox" checked={selected.has(t.id)} onChange={()=>toggle(t.id)}/><button type="button" className="drag-handle" onPointerDown={e=>{e.preventDefault();draggedRef.current=t.id;setDragged(t.id);setDragPoint({x:e.clientX,y:e.clientY});document.body.classList.add("task-dragging")}} title="拖动排序"><GripVertical size={17} pointerEvents="none"/></button><button type="button" className={`pin-button ${t.pinned?"active":""}`} onClick={()=>void action({operation:"pin",task_id:t.id,pinned:!t.pinned})} title={t.pinned?"取消固定":"固定灯位"}><Pin size={16}/></button></span><span className="slot"><i style={{background:t.color,boxShadow:`0 0 12px ${t.color}`}}/>{i<taskSlotCount?i+1:"未上灯"}</span><span className="task-name"><strong>{t.name}</strong><small>{new Date(t.updated).toLocaleString()}</small></span><span className="source">{t.source}</span><span><b className="badge" style={{color:t.color,background:`${t.color}18`}}>{t.state}</b></span></div>)}</div>
 {draggedTask&&dragPoint&&<div className="task-drag-ghost" style={{left:dragPoint.x,top:dragPoint.y}}><GripVertical size={16}/><i style={{background:draggedTask.color}}/><strong>{draggedTask.name}</strong></div>}
 </section></>}
function formatTokens(value:number){return value>=1000?`${(value/1000).toFixed(1)}K`:String(value)}
function Metric({icon,title,value,detail,tone}:{icon:React.ReactNode,title:string,value:string,detail:string,tone:string}){return <article className={`metric ${tone}`}><div className="metric-icon">{icon}</div><div><small>{title}</small><strong>{value}</strong><p>{detail}</p></div></article>}
function SettingsPage({brightness,setBrightness}:{brightness:number;setBrightness:(n:number)=>void}){const [styles,setStyles]=useState<Styles>(defaultStyles),[ledCount,setLedCount]=useState(6),[logs,setLogs]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem("operation-logs")||"[]").slice(0,100)}catch{return []}});useEffect(()=>{localStorage.setItem("operation-logs",JSON.stringify(logs.slice(0,100)))},[logs]);const log=(message:string)=>setLogs(old=>[`${new Date().toLocaleTimeString()}  ${message}`,...old].slice(0,100));return <div className="settings-grid"><div className="settings-main">
 <SystemLightEditor/>
 <DeviceSettings brightness={brightness} setBrightness={setBrightness} styles={styles} setStyles={setStyles} ledCount={ledCount} setLedCount={setLedCount} log={log}/>
 <EffectsEditor styles={styles} setStyles={setStyles}/>
 <OperationLog logs={logs} clear={()=>setLogs([])}/>
 </div><div className="settings-side"><section className="card compact"><div className="setting-title"><Wifi/><div><h2>数据源</h2><p>任务状态采集</p></div></div>{["Codex","Claude Code","Gemini CLI","Cursor"].map((x,i)=><div className="source-row" key={x}><span className="app-icon">{i===0?<Check size={14}/>:x[0]}</span><div><strong>{x}</strong><small>{i===0?"正在运行":"可用"}</small></div><Toggle on={i===0}/></div>)}<button className="full">管理数据源</button></section><section className="notice"><CircleAlert/><div><strong>所有数据仅保存在本机</strong><p>任务内容不会上传到外部服务。</p></div></section></div></div>}
function SystemLightEditor(){const defaults={task:30,token:20,cpu:20,memory:10,disk:10,network:10};const [weights,setWeights]=useState<Record<string,number>>(defaults),[source,setSource]=useState("账号余量"),[effect,setEffect]=useState(4);useEffect(()=>{invoke<{busy_weights:Record<string,number>;system_color_source:string;system_effect:number}>("bridge_action",{action:"settings",payload:{}}).then(data=>{setWeights(data.busy_weights||defaults);setSource(data.system_color_source||"账号余量");setEffect(data.system_effect||4)})},[]);const save=useCallback(()=>invoke("bridge_action",{action:"save-settings",payload:{busy_weights:weights,system_color_source:source,system_effect:effect}}),[weights,source,effect]);useEffect(()=>{const handler=()=>void save();window.addEventListener("save-and-apply",handler);return()=>window.removeEventListener("save-and-apply",handler)},[save]);const changeEffect=(value:number)=>{setEffect(value);void invoke("bridge_action",{action:"save-settings",payload:{system_effect:value}})};const labels:Record<string,string>={task:"任务数",token:"Token",cpu:"CPU",memory:"内存",disk:"磁盘",network:"网络"};const total=Object.values(weights).reduce((sum,value)=>sum+value,0);return <section className="card setting-card"><div className="setting-title"><Cpu/><div><h2>第一颗灯 · 系统状态</h2><p>颜色表示可用程度，动画速度表示综合繁忙度</p></div></div><div className="system-source"><label>灯光行为<select value={effect} onChange={e=>changeEffect(+e.target.value)}><option value="1">常亮</option><option value="2">闪烁</option><option value="3">呼吸</option><option value="4">双闪</option></select></label><label>颜色指标来源<select value={source} onChange={e=>setSource(e.target.value)}><option>CPU 可用程度</option><option>内存可用程度</option><option>磁盘可用程度</option><option>账号余量</option></select></label><small>绿色表示最可用，随可用程度降低平滑过渡到红色</small></div><div className="weight-grid">{Object.entries(weights).map(([key,value])=><label key={key}><span>{labels[key]}</span><input type="number" min="0" max="100" value={value} onChange={e=>setWeights({...weights,[key]:Math.max(0,Math.min(100,+e.target.value))})}/><em>%</em></label>)}</div><p className="formula">综合繁忙度 = 任务数 × {weights.task} + Token × {weights.token} + CPU × {weights.cpu} + 内存 × {weights.memory} + 磁盘 × {weights.disk} + 网络 × {weights.network}；当前合计 {total}，计算时自动归一化。</p></section>}
function DeviceSettings({brightness,setBrightness,styles,setStyles,ledCount,setLedCount,log}:{brightness:number;setBrightness:(n:number)=>void;styles:Styles;setStyles:(x:Styles)=>void;ledCount:number;setLedCount:(n:number)=>void;log:(message:string)=>void}){
 type Device={name:string;device_id:string;address:string;rssi:number};
 const [status,setStatus]=useState("点击管理附近灯板"),[devices,setDevices]=useState<Device[]>([]),[bound,setBound]=useState<string|null>(null),[sleep,setSleep]=useState(10),[channels,setChannels]=useState(1),[managerOpen,setManagerOpen]=useState(false),[selected,setSelected]=useState<Device|null>(null),[scanning,setScanning]=useState(false);
 useEffect(()=>{invoke<{bound_device_id:string|null;brightness:number;sleep_minutes:number;output_channels:number;led_count:number;styles:Styles}>("bridge_action",{action:"settings",payload:{}}).then(x=>{setBound(x.bound_device_id);setBrightness(x.brightness);setSleep(x.sleep_minutes);setChannels(x.output_channels||1);setLedCount(x.led_count);setStyles(x.styles)}).catch(e=>setStatus(String(e)))},[setBrightness,setLedCount,setStyles]);
 const action=async(name:string,payload:object)=>invoke<Record<string,unknown>>("bridge_action",{action:name,payload});
 const scan=async()=>{setScanning(true);setStatus("正在扫描…");try{const result=await invoke<{devices:Device[]}>("scan_devices");setDevices(result.devices);setSelected(result.devices.find(d=>d.device_id===bound)??result.devices[0]??null);setStatus(result.devices.length?`发现 ${result.devices.length} 块灯板`:"未发现灯板");log(`扫描完成，发现 ${result.devices.length} 块灯板`)}catch(error){setStatus(String(error));log(`扫描失败：${String(error)}`)}finally{setScanning(false)}};
 const openManager=()=>{setManagerOpen(true);void scan()};
 const bind=async(device:Device)=>{setStatus(`正在连接 ${device.name}…`);try{await action("save-settings",{bound_device_id:device.device_id});await action("apply-device",{master_brightness:brightness,sleep_timeout_minutes:sleep,total_led_count:ledCount,output_channels:channels,state_styles:styles});setBound(device.device_id);setStatus(`已连接并绑定 ${device.name}`);log(`已绑定 ${device.name}`)}catch(e){setStatus(`绑定配置下发失败：${String(e)}`);log(`绑定配置下发失败：${String(e)}`)}};
 const unbind=async()=>{await action("save-settings",{bound_device_id:null});setBound(null);setStatus("已取消绑定");log("已取消设备绑定")};
 const apply=async()=>{setStatus("正在连接并下发配置…");try{await action("apply-device",{master_brightness:brightness,sleep_timeout_minutes:sleep,total_led_count:ledCount,output_channels:channels,state_styles:styles});setStatus("配置已保存并下发");log("配置已保存并下发");window.dispatchEvent(new CustomEvent("save-result",{detail:"success"}))}catch(e){setStatus(String(e));log(`配置下发失败：${String(e)}`);window.dispatchEvent(new CustomEvent("save-result",{detail:"error"}))}};
 const identify=async(device:Device)=>{setStatus("正在识别…");try{await action("identify",{address:device.address});setStatus("识别动画已发送")}catch(e){setStatus(String(e))}};
 const upload=async(file:File)=>{setStatus("正在读取 OTA 固件…");const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));try{await action("ota",{firmware_base64:btoa(binary)});setStatus("OTA 已发送，灯板正在重启")}catch(e){setStatus(String(e))}};
 useEffect(()=>{const save=()=>void apply();window.addEventListener("save-and-apply",save);return()=>window.removeEventListener("save-and-apply",save)});
 return <section className="card setting-card"><div className="setting-title"><Lightbulb/><div><h2>灯板</h2><p>控制硬件连接和全局显示参数</p></div></div><div className="setting-row"><div><strong>{bound?`已绑定 · ${bound}`:"尚未绑定灯板"}</strong><small>{status}</small></div><button onClick={openManager}>设备管理</button></div><div className="setting-row"><div><strong>总灯数</strong><small>包含第一颗系统状态灯</small></div><input type="number" min="2" max="64" value={ledCount} onChange={e=>setLedCount(Math.max(2,Math.min(64,+e.target.value)))}/></div><div className="setting-row"><div><strong>灯带输出通道</strong><small>通道一固定 GPIO8；通道二使用 GPIO10</small></div><select value={channels} onChange={e=>setChannels(+e.target.value)}><option value="1">单通道（默认）</option><option value="2">双通道</option></select></div><div className="setting-row"><div><strong>整体亮度</strong><small>保存后下发到灯板</small></div><div className="range"><input type="range" min="1" max="100" value={brightness} onChange={e=>setBrightness(+e.target.value)}/><b>{brightness}%</b></div></div><div className="setting-row"><div><strong>断连后休眠</strong><small>设备断开连接后自动熄灯</small></div><select value={sleep} onChange={e=>setSleep(+e.target.value)}><option value="5">5 分钟</option><option value="10">10 分钟</option><option value="30">30 分钟</option></select></div><div className="setting-row"><button onClick={()=>void apply()}>保存并下发</button><label className="full">BLE OTA <input type="file" accept=".bin" onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/></label></div>{managerOpen&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setManagerOpen(false)}><div className="device-modal"><div className="modal-head"><div><h2>设备管理</h2><p>选择一块灯板进行识别或绑定</p></div><button className="icon-button" onClick={()=>setManagerOpen(false)}><X size={18}/></button></div><div className="device-table"><div className="device-table-head"><span>设备</span><span>唯一 ID</span><span>信号</span><span>状态</span></div>{devices.map(device=><button className={`device-row ${selected?.device_id===device.device_id?"selected":""}`} key={device.device_id} onClick={()=>setSelected(device)}><span><strong>{device.name}</strong><small>{device.address}</small></span><span>{device.device_id}</span><span>{device.rssi} dBm</span><span>{bound===device.device_id?"已绑定":"可绑定"}</span></button>)}{!devices.length&&!scanning&&<div className="empty-device">没有发现附近的灯板</div>}</div><div className="modal-status">{scanning?"正在扫描附近设备…":status}</div><div className="modal-actions"><button onClick={()=>void scan()} disabled={scanning}>{scanning?"扫描中…":"重新扫描"}</button><span/><button disabled={!selected} onClick={()=>selected&&void identify(selected)}>识别</button>{selected&&bound===selected.device_id?<button className="danger" onClick={()=>void unbind()}>取消绑定</button>:<button className="primary" disabled={!selected} onClick={()=>selected&&void bind(selected)}>绑定选中设备</button>}</div></div></div>}</section>}

function EffectsEditor({styles,setStyles}:{styles:Styles;setStyles:(x:Styles)=>void}){const names:Record<string,string>={running:"进行中",waiting:"等待操作",success:"已完成",warning:"警告",failure:"失败"};const update=(key:string,patch:Partial<StyleConfig>)=>setStyles({...styles,[key]:{...styles[key],...patch}});return <section className="card setting-card"><div className="setting-title"><Sparkles/><div><h2>任务灯效</h2><p>编辑后点击上方“保存并下发”生效</p></div></div><p className="auto-frequency-help">自动频率（按每个任务的工作量独立计算；即使任务状态相同，不同灯的频率也可能不同。关闭后，同一状态统一使用手动频率。）</p><div className="effect-list">{Object.entries(styles).map(([key,e])=><div className="effect" key={key}><input type="color" value={e.color} onChange={x=>update(key,{color:x.target.value})}/><strong>{names[key]}</strong><select value={e.effect} onChange={x=>{const effect=+x.target.value;update(key,{effect,automatic:effect===1?false:e.effect===1?true:e.automatic})}}><option value="1">常亮</option><option value="2">闪烁</option><option value="3">呼吸</option><option value="4">双闪</option></select>{e.effect!==1&&<label className="automatic-field"><input type="checkbox" checked={e.automatic} onChange={x=>update(key,{automatic:x.target.checked})}/> 自动</label>}{e.effect!==1&&!e.automatic&&<label>频率 <input type="number" min="6" max="300" value={e.frequency} onChange={x=>update(key,{frequency:+x.target.value})}/></label>}{e.effect===2&&!e.automatic&&<label>占空比 <input type="number" min="1" max="100" value={e.duty} onChange={x=>update(key,{duty:+x.target.value})}/></label>}</div>)}</div></section>}
function OperationLog({logs,clear}:{logs:string[];clear:()=>void}){const [open,setOpen]=useState(false);return <section className={`card operation-log-card ${open?"open":""}`}><button type="button" className="operation-log-head" onClick={()=>setOpen(value=>!value)}><span><strong>操作日志</strong><small>最近 {logs.length} 条人工操作记录，最多保留 100 条</small></span><b>{open?"收起":"展开"}</b></button>{open&&<div className="operation-log-body"><div className="operation-log-tools"><span>最新记录显示在最上方</span><button onClick={event=>{event.stopPropagation();clear()}}>一键清空</button></div><div className="operation-log-list">{logs.length?logs.map((line,index)=><p key={`${line}-${index}`}>{line}</p>):<small>暂无人工操作记录</small>}</div></div>}</section>}
export default App;
